import { Separator } from "@/components/ui/separator";
import { ScrollText } from "lucide-react";

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div className="flex items-center gap-3">
        <ScrollText className="text-primary h-8 w-8" />
        <div>
          <h1 className="text-2xl font-bold tracking-tight">
            Terms of Service
          </h1>
          <p className="text-muted-foreground">Last updated: April 10, 2026</p>
        </div>
      </div>

      <Separator />

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
        <section>
          <h2 className="text-lg font-semibold">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground">
            By accessing or using ContentOS Studio at contentosstudio.com, you
            agree to be bound by these Terms of Service. If you do not agree,
            you may not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">2. Description of Service</h2>
          <p className="text-muted-foreground">
            ContentOS Studio is a content production system that helps creators
            generate, manage, and optimise short-form video scripts using AI.
            The service includes script generation, Brand Brain personalisation,
            series creation, trend-based generation, cross-platform remixing,
            and performance analysis tools.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">3. Account Registration</h2>
          <p className="text-muted-foreground">
            You must create an account to use ContentOS Studio. You are
            responsible for maintaining the confidentiality of your account
            credentials and for all activity under your account. You must
            provide accurate information during registration.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">
            4. Subscriptions and Payment
          </h2>
          <ul className="text-muted-foreground list-disc space-y-1 pl-6">
            <li>
              <strong>Free tier</strong> — limited script generations per month.
            </li>
            <li>
              <strong>Paid tier</strong> — higher generation limit, billed
              monthly through Stripe.
            </li>
            <li>
              <strong>Extra credits</strong> — one-time purchase of 5 additional
              script generations for £2.99.
            </li>
            <li>
              <strong>Referrals</strong> — earn 1 bonus script generation per
              successful referral.
            </li>
            <li>
              Subscriptions auto-renew unless cancelled. You may cancel at any
              time through the Billing page or Stripe customer portal.
            </li>
            <li>
              Refunds are handled on a case-by-case basis. Contact support for
              assistance.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">5. Acceptable Use</h2>
          <p className="text-muted-foreground">You agree not to:</p>
          <ul className="text-muted-foreground list-disc space-y-1 pl-6">
            <li>Use the service for any unlawful purpose.</li>
            <li>
              Attempt to circumvent rate limits, usage limits, or security
              measures.
            </li>
            <li>
              Use automated tools to access the service beyond normal browser
              usage.
            </li>
            <li>
              Generate content that is hateful, violent, or violates the rights
              of others.
            </li>
            <li>Resell or redistribute the service without authorisation.</li>
            <li>
              Reverse engineer or attempt to extract the source code of the
              service.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">6. Content Ownership</h2>
          <p className="text-muted-foreground">
            You retain ownership of all scripts and content you create using
            ContentOS Studio. We do not claim intellectual property rights over
            your generated content. However, we may use anonymised, aggregated
            usage data to improve the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">7. AI-Generated Content</h2>
          <p className="text-muted-foreground">
            Scripts are generated by AI (Anthropic Claude) based on your inputs
            and Brand Brain context. We do not guarantee the accuracy,
            originality, or suitability of AI-generated content. You are
            responsible for reviewing and editing all generated scripts before
            use. AI-generated content should not be relied upon as factual
            without verification.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">8. YouTube Data</h2>
          <p className="text-muted-foreground">
            When using YouTube-related features (trends, analyzer), you agree to
            comply with the{" "}
            <a
              href="https://www.youtube.com/t/terms"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary underline underline-offset-4"
            >
              YouTube Terms of Service
            </a>{" "}
            and{" "}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary underline underline-offset-4"
            >
              Google Privacy Policy
            </a>
            . YouTube data is used solely to provide trend suggestions and
            performance insights within the platform.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">9. Service Availability</h2>
          <p className="text-muted-foreground">
            We strive to maintain high availability but do not guarantee
            uninterrupted service. We may perform maintenance, updates, or
            experience downtime due to third-party service disruptions. We are
            not liable for any losses resulting from service unavailability.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">10. Limitation of Liability</h2>
          <p className="text-muted-foreground">
            To the maximum extent permitted by law, ContentOS Studio and its
            operators shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, including loss of revenue,
            profits, or data, arising from your use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">11. Termination</h2>
          <p className="text-muted-foreground">
            We may suspend or terminate your account if you violate these terms.
            You may delete your account at any time. Upon termination, your
            access to the service will cease and your data will be deleted in
            accordance with our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">12. Changes to Terms</h2>
          <p className="text-muted-foreground">
            We reserve the right to modify these terms at any time. Continued
            use of the service after changes constitutes acceptance. Material
            changes will be communicated via email or in-app notification.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">13. Governing Law</h2>
          <p className="text-muted-foreground">
            These terms are governed by the laws of England and Wales. Any
            disputes shall be subject to the exclusive jurisdiction of the
            courts of England and Wales.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">14. Contact</h2>
          <p className="text-muted-foreground">
            Questions about these terms? Contact us through the Help page or
            email support@contentosstudio.com.
          </p>
        </section>
      </div>
    </div>
  );
}
